name: Build

on:
  workflow_call:
    inputs:
      ruby_version:
        type: string
        required: true
    secrets:
      bundle_github__com:
        required: false
      rails_master_key:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build rails
        uses: ePages-de/action-build-rails@master
        with:
          ruby_version: ${{ inputs.ruby_version }}
          bundle_github__com: ${{ secrets.bundle_github__com }}

  rubocop:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: ePages-de/action-ruby-run@master
        with:
          ruby_version: ${{ inputs.ruby_version }}
          bundle_github__com: ${{ secrets.bundle_github__com }}
          cmd: bundle exec rubocop --config .rubocop.yml

  rspec:
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      CI: true
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
      RAILS_ENV: test
      REDIS_URL: redis://localhost:6379/0
      RAILS_MASTER_KEY: ${{ secrets.rails_master_key }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GITHUB__COM: ${{ secrets.bundle_github__com }}
        with:
          ruby-version: ${{ inputs.ruby_version }}
          bundler-cache: true
      - run: sudo apt-get update
      - run: sudo apt-get -y install libpq-dev
      - run: sudo apt-get -y install libvips
      - run: bundle exec rails db:setup db:schema:load --trace
      - run: bundle exec rspec
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage
          path: coverage
