name: Linting Workflow

on:
  workflow_call:
    inputs:
      ruby-version:
        required: true
        type: string
      node-version:
        required: false
        type: string
    secrets:
      bundle_github__com:
        required: false

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true
        env:
          BUNDLE_GITHUB__COM: ${{ secrets.bundle_github__com }}
      - name: Rubocop
        run: bundle exec rubocop --config .rubocop.yml

  eslint:
    runs-on: ubuntu-latest
    if: ${{ inputs.node-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn
      - name: Yarn install
        run: yarn install --production=false
      - name: ES Lint
        run: npx eslint app
