name: Tests

on:
  workflow_call:
    inputs:
      ruby-version:
        type: string
        required: true
      node-version:
        type: string
        required: false
      node-version-file:
        type: string
        required: false
    secrets:
      bundle_github__com:
        required: false
      rails_master_key:
        required: false

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      CI: true
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
      RAILS_ENV: test
      REDIS_URL: redis://localhost:6379/0
      RAILS_MASTER_KEY: ${{ secrets.rails_master_key }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GITHUB__COM: ${{ secrets.bundle_github__com }}
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true
      - name: Setup Node
        if: ${{ inputs.node-version || inputs.node-version-file }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}
          cache: yarn
      - name: Yarn install
        if: ${{ inputs.node-version || inputs.node-version-file }}
        run: yarn install --production=false
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libpq-dev
          sudo apt-get -y install libvips
      - name: Setup database
        run: |
          bin/rails db:test:prepare
      - run: bundle exec rspec
